services:
  grafana:
    image: docker.io/grafana/grafana-enterprise:latest
    container_name: grafana-example
    restart: always
    env_file: 
      - ${ROOT_DIR}/.env
    volumes:
      - ${ROOT_DIR}/grafana-data:/var/lib/grafana
      - ${ROOT_DIR}/sqlite-data:/db
    depends_on:
      - data-generator
    network_mode: host
  
  data-generator:
    image: sqlite-data-generator
    container_name: data-generator-example
    restart: always
    env_file:
      - ${ROOT_DIR}/.env
    volumes:
      - ${ROOT_DIR}/sqlite-data:/workspace/sqlite-data
    network_mode: host
  