services:
  grafana:
    image: docker.io/grafana/grafana-enterprise:latest
    container_name: grafana-example
    restart: always
    env_file: 
      - ${ROOT_DIR}/.env
    user: "${UID}:${GID}"
    volumes:
      - ${ROOT_DIR}/grafana-data:/var/lib/grafana
      - ${ROOT_DIR}/sqlite-data:/db
    depends_on:
      - data-generator
    network_mode: host
  
  data-generator:
    build:
      context: ..
      dockerfile: docker/sqlite-data-generator.Dockerfile
    image: sqlite-data-generator
    container_name: sqlite-data-generator-example
    restart: always
    env_file:
      - ${ROOT_DIR}/.env
    user: "${UID}:${GID}"
    volumes:
      - ${ROOT_DIR}/sqlite-data:/workspace/sqlite-data
    network_mode: host
