services:
  grafana:
    image: docker.io/grafana/grafana-enterprise:12.0.1
    container_name: grafana-example
    restart: always
    env_file: 
      - ${ROOT_DIR}/.env
    environment:
      - GF_PLUGINS_PREINSTALL="frser-sqlite-datasource"
    user: "${UID}:${GID}"
    volumes:
      - ${ROOT_DIR}/grafana-data:/var/lib/grafana
      - ${ROOT_DIR}/sqlite-data:/db
    depends_on:
      - sqlite-data-generator
    network_mode: host
  
  sqlite-data-generator:
    build:
      context: ..
      dockerfile: docker/sqlite-data-generator.Dockerfile
    image: sqlite-data-generator-example
    container_name: sqlite-data-generator-example
    restart: always
    env_file:
      - ${ROOT_DIR}/.env
    user: "${UID}:${GID}"
    volumes:
      - ${ROOT_DIR}/sqlite-data:/workspace/sqlite-data
    network_mode: host
