version: "3.9"

services:
  nodered:
    image: node-red-custom  # Use the custom image
    container_name: NodeREDContainer
    restart: always
    ports:
      - "1880:1880"
    devices:
      - /dev/ttyCOM1:/dev/ttyCOM1
      - /dev/ttyCOM2:/dev/ttyCOM2
    group_add:
      - keep-groups
    volumes:
      - /data/user/node-red-podman/data:/data  # Persistent volume for flows and configurations
    stdin_open: true
    tty: true